export default {
  users: "users",
  invitations: "invitations",
  events: "events",
  tasks: "tasks",
  clients: "clients",
  notifications: "notifications",
  creditTransactions: "creditTransactions",
  claims: "claims",
  goals: "goals",
  chats: "chats",
  chatMessages: "chatMessages",
  competition: "competition",
  competitionDeal: "competitionDeal",
};
