export enum NotificationTypes {
  Invitation = "invitation",
  InvitationAccepted = "invitation_accepted",
  TaskCreated = "task_created",
  TaskAssigned = "task_assigned",
  GoalCreated = "goal_created",
  GoalClaimed = "goal_claimed",
  CompetitionCreation = "competition_creation",
  CompetitionUpdate = "competition_update",
  GoalAssigned = "goal_assigned",
  CashRewardCreated = "cash_reward_created",
  CashRewardClaimed = "cash_reward_claimed",
  CashRewardAssigned = "cash_reward_assigned",
  ProRewardCreated = "cash_reward_created",
  ProRewardClaimed = "cash_reward_claimed",
  ProRewardAssigned = "cash_reward_assigned",
  GoalSuggested = "goal_suggested",
  TaskStatusChanged = "task_status_changed",
  TaskDeclined = "task_declined",
  NewMessage = "new_message",
}
